spring.application.name=YouTube MP3 Downloader
server.port=8080

# Ruta a yt-dlp (ajustar si es necesario)
ytdlp.path=${user.home}/.local/bin/yt-dlp

# Timeout para requests asincronos (10 minutos)
spring.mvc.async.request-timeout=600000
